package Exception.Q4;

public class Q4 {

    public static void main(String[] args) {
        // Case 1
//        try{
//            System.out.println(98/0);
//        }
//        catch(ArithmeticException ae){
//            System.out.println("Arithmetic Exception occurs !!");
//        }
//        finally{
//            System.out.println("Finally block occurs !!");
//        }

        // Case 2
//        try{
//            System.out.println("Try block occurs !!");
//        }
//        finally{
//            System.out.println("Finally block occurs !!");
//        }
    }
}
